In [1]:


import pandas as pd
import numpy as np
import tensorflow as tf

from tensorflow.keras import layers

In [2]:
tf.__version__

'2.8.2'

In [3]:
#reading the dataset

hourly_samples_path = 'https://drive.google.com/uc?export=download&id=1di7YkJN_eXvq3xkKj2dPp4Z0Rc9qhlkQ'
dataframe = pd.read_csv(hourly_samples_path)

#https://drive.google.com/file/d/1di7YkJN_eXvq3xkKj2dPp4Z0Rc9qhlkQ/view?usp=sharing
#https://drive.google.com/file/d/1di7YkJN_eXvq3xkKj2dPp4Z0Rc9qhlkQ/view?usp=sharing
#https://drive.google.com/file/d/1di7YkJN_eXvq3xkKj2dPp4Z0Rc9qhlkQ/view?usp=sharing

In [4]:
dataframe = dataframe.convert_dtypes()
print(dataframe.dtypes)

station_key               Int64
full_name                string
latitude                Float64
longitude               Float64
daily_total               Int64
day_of_week               Int64
public_holiday            Int64
school_holiday            Int64
time (hours)             string
traffic_hourly_count      Int64
threshold               Float64
dtype: object

In [5]:
#traffic_max = df['time (hours)':['hour_00', 'hour_01', 'hour_02', 'hour_03', 'hour_04', 'hour_05', 'hour_06', 'hour_07', 'hour_08', 'hour_09', 'hour_10', 'hour_11', 'hour_12', 'hour_13', 'hour_14', 'hour_15', 'hour_16', 'hour_17', 'hour_17', 'hour_18', 'hour_19', 'hour_20', 'hour_21', 'hour_22', 'hour_23']].max(axis=1)
dataframe.head()

,station_key,full_name,latitude,longitude,daily_total,day_of_week,public_holiday,school_holiday,time (hours),traffic_hourly_count,threshold
0,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_00,863,690.4
1,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_01,602,690.4
2,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_02,503,690.4
3,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_03,604,690.4
4,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_04,855,690.4

In [6]:
dataframe['congested'] = np.where(dataframe.traffic_hourly_count >= dataframe.threshold, 0, 1)
dataframe.head(10)

,station_key,full_name,latitude,longitude,daily_total,day_of_week,public_holiday,school_holiday,time (hours),traffic_hourly_count,threshold,congested
0,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_00,863,690.4,0
1,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_01,602,690.4,1
2,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_02,503,690.4,1
3,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_03,604,690.4,1
4,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_04,855,690.4,0
5,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_05,1595,690.4,0
6,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_06,3052,690.4,0
7,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_07,3852,690.4,0
8,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_08,3948,690.4,0
9,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_09,3280,690.4,0

In [7]:
# Drop unused features.
dataframe['target'] = np.where(dataframe['congested']==4,0, 1)

dataframe = dataframe.drop(columns=['threshold', 'congested'])

In [8]:
dataframe.head()

,station_key,full_name,latitude,longitude,daily_total,day_of_week,public_holiday,school_holiday,time (hours),traffic_hourly_count,target
0,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_00,863,1
1,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_01,602,1
2,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_02,503,1
3,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_03,604,1
4,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,hour_04,855,1

In [9]:
print(dataframe.ndim)

2

In [10]:
train, val, test = np.split(dataframe.sample(frac=1), [int(0.8*len(dataframe)), int(0.9*len(dataframe))])

In [11]:
print(len(train), 'training examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

288 training examples
36 validation examples
36 test examples

In [12]:
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  df = dataframe.copy()
  labels = df.pop('target')
  df = {key: value[:,tf.newaxis] for key, value in dataframe.items()}
  ds = tf.data.Dataset.from_tensor_slices((dict(df), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  ds = ds.prefetch(batch_size)
  return ds

In [13]:
batch_size = 5
train_ds = df_to_dataset(train, batch_size=batch_size)

ValueError: ignored