In [ ]:
import pandas as pd
import numpy as np

In [ ]:
hourlyDF = pd.read_csv('/content/road_traffic_counts_hourly_sample.csv')
stationDF = pd.read_csv('/content/road_traffic_counts_station_reference.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (12,13,40) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

* station_key	
* full_name	
* latitude	
* longitude	
* daily_total	
* day_of_week	
* public_holiday	
* school_holiday	
* hour_00	
* hour_01	
* hour_02	
* hour_03	
* hour_04	
* hour_05	
* hour_06	
* hour_07	
* hour_08	
* hour_09	
* hour_10	
* hour_11	
* hour_12	
* hour_13	
* hour_14	
* hour_15	
* hour_16	
* hour_17	
* hour_18	
* hour_19	
* hour_20	
* hour_21	
* hour_22	
* hour_23	
* congestion_threshold

In [ ]:
finalDF = pd.merge(hourlyDF, stationDF, 
                   on='station_key', 
                   how='left')

In [ ]:
pd.set_option("display.max_columns", None)

In [ ]:
drop_columns1 = finalDF.iloc[:, 0:4]
drop_columns2 = finalDF.iloc[:, 5:11]
drop_columns3 = finalDF.iloc[:, 39:48]
drop_columns4 = finalDF.iloc[:, 49:75]
drop_columns5 = finalDF.iloc[:, 77:82]

finalDF = finalDF.drop(drop_columns1, axis=1)
finalDF = finalDF.drop(drop_columns2, axis=1)
finalDF = finalDF.drop(drop_columns3, axis=1)
finalDF = finalDF.drop(drop_columns4, axis=1)
finalDF = finalDF.drop(drop_columns5, axis=1)

finalDF = finalDF.dropna()

finalDF.tail()

,station_key,day_of_week,public_holiday,school_holiday,daily_total,hour_00,hour_01,hour_02,hour_03,hour_04,hour_05,hour_06,hour_07,hour_08,hour_09,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,full_name,wgs84_latitude,wgs84_longitude
98879,328023,4,0,0,274,4.0,1.0,2.0,1.0,1.0,7.0,16.0,15.0,24.0,15.0,20.0,15.0,19.0,15.0,23.0,16.0,20.0,14.0,13.0,10.0,9.0,4.0,4.0,6.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534
98880,328023,1,0,0,297,2.0,3.0,3.0,2.0,1.0,4.0,4.0,21.0,18.0,23.0,11.0,13.0,24.0,25.0,30.0,21.0,22.0,18.0,15.0,11.0,7.0,8.0,6.0,5.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534
98881,328023,3,0,0,306,1.0,4.0,3.0,1.0,1.0,10.0,12.0,18.0,24.0,16.0,16.0,21.0,23.0,36.0,20.0,20.0,20.0,15.0,13.0,7.0,9.0,3.0,8.0,5.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534
98882,328024,1,1,1,1121,3.0,3.0,1.0,4.0,4.0,17.0,31.0,38.0,50.0,101.0,124.0,127.0,99.0,100.0,120.0,78.0,64.0,60.0,36.0,26.0,16.0,10.0,2.0,7.0,"Castlereagh Highway, West of Melrose Road",-32.649929,149.661560
98883,328024,2,0,1,947,5.0,2.0,2.0,1.0,5.0,19.0,25.0,45.0,48.0,63.0,85.0,87.0,83.0,73.0,74.0,82.0,77.0,75.0,46.0,20.0,11.0,12.0,5.0,2.0,"Castlereagh Highway, West of Melrose Road",-32.649929,149.661560

In [ ]:
finalDF['threshold'] = finalDF[['hour_00', 'hour_01', 'hour_02', 'hour_03', 'hour_04', 'hour_05', 
                                'hour_06', 'hour_07', 'hour_08', 'hour_09', 'hour_10', 'hour_11', 
                                'hour_12', 'hour_13', 'hour_14', 'hour_15', 'hour_16', 'hour_17', 
                                'hour_18', 'hour_19', 'hour_20', 'hour_21', 'hour_22', 'hour_23']].max(axis=1)

finalDF.loc[:,'threshold'] *= 0.8

In [ ]:
finalDF.tail()

,station_key,day_of_week,public_holiday,school_holiday,daily_total,hour_00,hour_01,hour_02,hour_03,hour_04,hour_05,hour_06,hour_07,hour_08,hour_09,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,full_name,wgs84_latitude,wgs84_longitude,threshold
98879,328023,4,0,0,274,4.0,1.0,2.0,1.0,1.0,7.0,16.0,15.0,24.0,15.0,20.0,15.0,19.0,15.0,23.0,16.0,20.0,14.0,13.0,10.0,9.0,4.0,4.0,6.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,19.2
98880,328023,1,0,0,297,2.0,3.0,3.0,2.0,1.0,4.0,4.0,21.0,18.0,23.0,11.0,13.0,24.0,25.0,30.0,21.0,22.0,18.0,15.0,11.0,7.0,8.0,6.0,5.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,24.0
98881,328023,3,0,0,306,1.0,4.0,3.0,1.0,1.0,10.0,12.0,18.0,24.0,16.0,16.0,21.0,23.0,36.0,20.0,20.0,20.0,15.0,13.0,7.0,9.0,3.0,8.0,5.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,28.8
98882,328024,1,1,1,1121,3.0,3.0,1.0,4.0,4.0,17.0,31.0,38.0,50.0,101.0,124.0,127.0,99.0,100.0,120.0,78.0,64.0,60.0,36.0,26.0,16.0,10.0,2.0,7.0,"Castlereagh Highway, West of Melrose Road",-32.649929,149.661560,101.6
98883,328024,2,0,1,947,5.0,2.0,2.0,1.0,5.0,19.0,25.0,45.0,48.0,63.0,85.0,87.0,83.0,73.0,74.0,82.0,77.0,75.0,46.0,20.0,11.0,12.0,5.0,2.0,"Castlereagh Highway, West of Melrose Road",-32.649929,149.661560,69.6

In [ ]:
finalDF.drop(finalDF.index[finalDF['daily_total'] < 500], inplace = True)

In [ ]:
finalDF.tail()

,station_key,day_of_week,public_holiday,school_holiday,daily_total,hour_00,hour_01,hour_02,hour_03,hour_04,hour_05,hour_06,hour_07,hour_08,hour_09,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,full_name,wgs84_latitude,wgs84_longitude,threshold
98872,328023,4,0,0,1904,1.0,3.0,4.0,1.0,8.0,25.0,91.0,114.0,213.0,131.0,106.0,115.0,126.0,120.0,126.0,157.0,144.0,144.0,110.0,69.0,43.0,24.0,22.0,7.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,170.4
98873,328023,3,0,0,1807,4.0,4.0,2.0,1.0,8.0,27.0,87.0,134.0,223.0,131.0,113.0,106.0,115.0,115.0,124.0,128.0,126.0,114.0,75.0,69.0,48.0,32.0,14.0,7.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,178.4
98874,328023,2,0,0,1761,2.0,3.0,3.0,4.0,9.0,29.0,64.0,108.0,218.0,130.0,127.0,109.0,108.0,126.0,114.0,115.0,118.0,146.0,73.0,55.0,46.0,27.0,19.0,8.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,174.4
98882,328024,1,1,1,1121,3.0,3.0,1.0,4.0,4.0,17.0,31.0,38.0,50.0,101.0,124.0,127.0,99.0,100.0,120.0,78.0,64.0,60.0,36.0,26.0,16.0,10.0,2.0,7.0,"Castlereagh Highway, West of Melrose Road",-32.649929,149.661560,101.6
98883,328024,2,0,1,947,5.0,2.0,2.0,1.0,5.0,19.0,25.0,45.0,48.0,63.0,85.0,87.0,83.0,73.0,74.0,82.0,77.0,75.0,46.0,20.0,11.0,12.0,5.0,2.0,"Castlereagh Highway, West of Melrose Road",-32.649929,149.661560,69.6

In [ ]:
finalDF = finalDF.dropna()
finalDF.reset_index(level=None, drop=False, inplace=False, col_level=0, col_fill='')

,index,station_key,day_of_week,public_holiday,school_holiday,daily_total,hour_00,hour_01,hour_02,hour_03,hour_04,hour_05,hour_06,hour_07,hour_08,hour_09,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,full_name,wgs84_latitude,wgs84_longitude,threshold
0,11,58177,6,false,false,530,0.0,0.0,1.0,1.0,0.0,1.0,7.0,9.0,26.0,42.0,49.0,59.0,54.0,48.0,33.0,43.0,40.0,32.0,38.0,17.0,14.0,7.0,7.0,2.0,"Braidwood Road, South of Painters Lane",-34.876907,149.684677,47.2
1,68,57792,5,false,false,563,0.0,1.0,2.0,1.0,3.0,3.0,17.0,31.0,49.0,43.0,42.0,31.0,31.0,43.0,49.0,49.0,50.0,59.0,27.0,12.0,8.0,7.0,4.0,1.0,"Thunderbolts Way, North of Mirani Road",-30.859583,151.547974,47.2
2,94,57792,1,true,false,518,1.0,1.0,1.0,1.0,0.0,1.0,2.0,5.0,12.0,20.0,38.0,23.0,43.0,49.0,56.0,75.0,71.0,57.0,26.0,21.0,6.0,8.0,1.0,0.0,"Thunderbolts Way, North of Mirani Road",-30.859583,151.547974,60.0
3,108,58629,1,false,false,700,5.0,3.0,1.0,1.0,2.0,7.0,41.0,38.0,57.0,47.0,72.0,46.0,43.0,48.0,37.0,51.0,51.0,45.0,27.0,25.0,29.0,13.0,9.0,2.0,"Perricoota Road, West of Preston Road",-36.049980,144.654480,57.6
4,128,58177,6,false,false,575,6.0,4.0,1.0,1.0,0.0,1.0,8.0,26.0,24.0,34.0,42.0,41.0,50.0,52.0,61.0,42.0,44.0,49.0,37.0,18.0,8.0,10.0,8.0,8.0,"Braidwood Road, South of Painters Lane",-34.876907,149.684677,48.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76406,98872,328023,4,0,0,1904,1.0,3.0,4.0,1.0,8.0,25.0,91.0,114.0,213.0,131.0,106.0,115.0,126.0,120.0,126.0,157.0,144.0,144.0,110.0,69.0,43.0,24.0,22.0,7.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,170.4
76407,98873,328023,3,0,0,1807,4.0,4.0,2.0,1.0,8.0,27.0,87.0,134.0,223.0,131.0,113.0,106.0,115.0,115.0,124.0,128.0,126.0,114.0,75.0,69.0,48.0,32.0,14.0,7.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,178.4
76408,98874,328023,2,0,0,1761,2.0,3.0,3.0,4.0,9.0,29.0,64.0,108.0,218.0,130.0,127.0,109.0,108.0,126.0,114.0,115.0,118.0,146.0,73.0,55.0,46.0,27.0,19.0,8.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,174.4
76409,98882,328024,1,1,1,1121,3.0,3.0,1.0,4.0,4.0,17.0,31.0,38.0,50.0,101.0,124.0,127.0,99.0,100.0,120.0,78.0,64.0,60.0,36.0,26.0,16.0,10.0,2.0,7.0,"Castlereagh Highway, West of Melrose Road",-32.649929,149.661560,101.6
76410,98883,328024,2,0,1,947,5.0,2.0,2.0,1.0,5.0,19.0,25.0,45.0,48.0,63.0,85.0,87.0,83.0,73.0,74.0,82.0,77.0,75.0,46.0,20.0,11.0,12.0,5.0,2.0,"Castlereagh Highway, West of Melrose Road",-32.649929,149.661560,69.6

In [ ]:
finalDF.tail()

,station_key,day_of_week,public_holiday,school_holiday,daily_total,hour_00,hour_01,hour_02,hour_03,hour_04,hour_05,hour_06,hour_07,hour_08,hour_09,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,full_name,wgs84_latitude,wgs84_longitude,threshold
98872,328023,4,0,0,1904,1.0,3.0,4.0,1.0,8.0,25.0,91.0,114.0,213.0,131.0,106.0,115.0,126.0,120.0,126.0,157.0,144.0,144.0,110.0,69.0,43.0,24.0,22.0,7.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,170.4
98873,328023,3,0,0,1807,4.0,4.0,2.0,1.0,8.0,27.0,87.0,134.0,223.0,131.0,113.0,106.0,115.0,115.0,124.0,128.0,126.0,114.0,75.0,69.0,48.0,32.0,14.0,7.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,178.4
98874,328023,2,0,0,1761,2.0,3.0,3.0,4.0,9.0,29.0,64.0,108.0,218.0,130.0,127.0,109.0,108.0,126.0,114.0,115.0,118.0,146.0,73.0,55.0,46.0,27.0,19.0,8.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,174.4
98882,328024,1,1,1,1121,3.0,3.0,1.0,4.0,4.0,17.0,31.0,38.0,50.0,101.0,124.0,127.0,99.0,100.0,120.0,78.0,64.0,60.0,36.0,26.0,16.0,10.0,2.0,7.0,"Castlereagh Highway, West of Melrose Road",-32.649929,149.661560,101.6
98883,328024,2,0,1,947,5.0,2.0,2.0,1.0,5.0,19.0,25.0,45.0,48.0,63.0,85.0,87.0,83.0,73.0,74.0,82.0,77.0,75.0,46.0,20.0,11.0,12.0,5.0,2.0,"Castlereagh Highway, West of Melrose Road",-32.649929,149.661560,69.6

In [ ]:
cols = ["public_holiday","school_holiday"]
finalDF[cols] = finalDF[cols].replace({'0':False, '1':True, 0:False, 1:True})

In [ ]:
finalDF.tail()

,station_key,day_of_week,public_holiday,school_holiday,daily_total,hour_00,hour_01,hour_02,hour_03,hour_04,hour_05,hour_06,hour_07,hour_08,hour_09,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,full_name,wgs84_latitude,wgs84_longitude,threshold
98872,328023,4,False,False,1904,1.0,3.0,4.0,1.0,8.0,25.0,91.0,114.0,213.0,131.0,106.0,115.0,126.0,120.0,126.0,157.0,144.0,144.0,110.0,69.0,43.0,24.0,22.0,7.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,170.4
98873,328023,3,False,False,1807,4.0,4.0,2.0,1.0,8.0,27.0,87.0,134.0,223.0,131.0,113.0,106.0,115.0,115.0,124.0,128.0,126.0,114.0,75.0,69.0,48.0,32.0,14.0,7.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,178.4
98874,328023,2,False,False,1761,2.0,3.0,3.0,4.0,9.0,29.0,64.0,108.0,218.0,130.0,127.0,109.0,108.0,126.0,114.0,115.0,118.0,146.0,73.0,55.0,46.0,27.0,19.0,8.0,"Stewart Street, West of Griffin Street",-33.422489,149.556534,174.4
98882,328024,1,True,True,1121,3.0,3.0,1.0,4.0,4.0,17.0,31.0,38.0,50.0,101.0,124.0,127.0,99.0,100.0,120.0,78.0,64.0,60.0,36.0,26.0,16.0,10.0,2.0,7.0,"Castlereagh Highway, West of Melrose Road",-32.649929,149.661560,101.6
98883,328024,2,False,True,947,5.0,2.0,2.0,1.0,5.0,19.0,25.0,45.0,48.0,63.0,85.0,87.0,83.0,73.0,74.0,82.0,77.0,75.0,46.0,20.0,11.0,12.0,5.0,2.0,"Castlereagh Highway, West of Melrose Road",-32.649929,149.661560,69.6

In [ ]:
finalDF.to_csv(r'/finalDataset.csv', index = False)