In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
import sys

hourly_samples_path = 'https://drive.google.com/uc?export=download&id=13U6Ijmq936XUVYpbplqhde_Ypgna8DDl'
df = pd.read_csv(hourly_samples_path)

In [ ]:
df = df.fillna(0)

df.convert_dtypes()

df.drop(['Threshold (What it takes to congest the road)'], axis=1)

In [ ]:
max = df[['hour_00', 'hour_01', 'hour_02', 'hour_03', 'hour_04', 'hour_05', 'hour_06', 'hour_07', 'hour_08', 'hour_09', 'hour_10', 'hour_11', 'hour_12', 'hour_13', 'hour_14', 'hour_15', 'hour_16', 'hour_17', 'hour_17', 'hour_18', 'hour_19', 'hour_20', 'hour_21', 'hour_22', 'hour_23']].max(axis=1)

df['threshold'] = max * 0.75

print (df)

In [30]:
df.head(2)

,station_key,full_name,latitude,longitude,daily_total,day_of_week,public_holiday,school_holiday,hour_00,hour_01,...,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,Threshold (What it takes to congest the road),threshold
0,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,5,0,0,863,602,...,4759,5059,4182,3118,2010,1727,2965,2655,4300.15,4025.25
1,56667,"Southern Cross Drive, East of Mill Pond Drive",-33.936520,151.198883,60571,5,0,0,173,112,...,3601,3945,4005,3279,2363,1990,1660,845,3353.25,3489.00

In [3]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
import sys

def main():

  hourly_samples_path = 'https://drive.google.com/uc?export=download&id=13U6Ijmq936XUVYpbplqhde_Ypgna8DDl'
  df = pd.read_csv(hourly_samples_path)

  df.groupby(['station_key']) #group the data by station

  x, y = pre_processing(df)
  x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=10)

  model = LinearRegression()
  model.fit(x_train,y_train)

  evaluate(model, x_train, y_train, x_test, y_test)

def pre_processing(dataframe):
  features = dataframe.iloc[0:20, 10:39]
  #columns_drop = ["day_of_week", "public_holiday", "school_holiday"]
  #features = features.drop(columns_drop, axis=1)
  target = dataframe.iloc[0:20, 4]
  return features, target



def evaluate(model, x_train, y_train, x_test, y_test ):
  if(model == None):
    print("Model does not exist")
    return
  print(f"Train accuracy {model.score(x_train,y_train)} ")
  print(f"Test accuracy {model.score(x_test,y_test)} ")
  return

main()

Train accuracy 1.0
Test accuracy -2.406900256348991