In [1]:

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split, KFold, cross_val_score

import sys

from sklearn.metrics import accuracy_score

In [2]:

#df = 'https://drive.google.com/uc?export=download&id=19DIL99UGIzhPZQ_VDuyrDmGPvy5VMGAn'

df = 'https://drive.google.com/uc?export=download&id=1CE5IoJSha20kZE8H5gT9XRo33U0Fzub8'
raw_dataset = pd.read_csv(df)

In [3]:
dataset = raw_dataset.copy()
pd.set_option("display.max_columns", None)
dataset.head()

,station_key,day_of_week,public_holiday,school_holiday,daily_total,hour_00,hour_01,hour_02,hour_03,hour_04,hour_05,hour_06,hour_07,hour_08,hour_09,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,full_name,wgs84_latitude,wgs84_longitude,threshold
0,58177,6,False,False,530,0.0,0.0,1.0,1.0,0.0,1.0,7.0,9.0,26.0,42.0,49.0,59.0,54.0,48.0,33.0,43.0,40.0,32.0,38.0,17.0,14.0,7.0,7.0,2.0,"Braidwood Road, South of Painters Lane",-34.876907,149.684677,47.2
1,57792,5,False,False,563,0.0,1.0,2.0,1.0,3.0,3.0,17.0,31.0,49.0,43.0,42.0,31.0,31.0,43.0,49.0,49.0,50.0,59.0,27.0,12.0,8.0,7.0,4.0,1.0,"Thunderbolts Way, North of Mirani Road",-30.859583,151.547974,47.2
2,57792,1,True,False,518,1.0,1.0,1.0,1.0,0.0,1.0,2.0,5.0,12.0,20.0,38.0,23.0,43.0,49.0,56.0,75.0,71.0,57.0,26.0,21.0,6.0,8.0,1.0,0.0,"Thunderbolts Way, North of Mirani Road",-30.859583,151.547974,60.0
3,58629,1,False,False,700,5.0,3.0,1.0,1.0,2.0,7.0,41.0,38.0,57.0,47.0,72.0,46.0,43.0,48.0,37.0,51.0,51.0,45.0,27.0,25.0,29.0,13.0,9.0,2.0,"Perricoota Road, West of Preston Road",-36.049980,144.654480,57.6
4,58177,6,False,False,575,6.0,4.0,1.0,1.0,0.0,1.0,8.0,26.0,24.0,34.0,42.0,41.0,50.0,52.0,61.0,42.0,44.0,49.0,37.0,18.0,8.0,10.0,8.0,8.0,"Braidwood Road, South of Painters Lane",-34.876907,149.684677,48.8

In [12]:
def pre_processing(dataframe):
    features = dataframe.iloc[:, 0:32]
    #columns_drop = ['station_key', 'day_of_week', 'public_holiday', 'school_holiday', 'full_name', 'latitude', 'longitude', 'daily_total']
    columns_drop = ['station_key', 'day_of_week', 'school_holiday', 'full_name', 'wgs84_latitude', 'wgs84_longitude', 'daily_total']
    features = features.drop(columns_drop, axis=1)
    dataframe = dataset.dropna()
    target = dataframe.iloc[:, 32]
    
    return features, target

In [13]:
def evaluate(model, x_train, y_train, x_test, y_test ):
    if(model == None):
        print("Model does not exist")
        return

    print(f"Train accuracy {model.score(x_train,y_train)} ")
    print(f"Test accuracy {model.score(x_test,y_test)} ")
    return

In [14]:
def cross_validation(dataset, model, x, y):
  k = 5
  kf = KFold(n_splits=k, random_state=None)
  
  result = cross_val_score(model , x, y, cv = kf)
  print("Avg accuracy: {}".format(result.mean()))

In [15]:
x, y = pre_processing(dataset)
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=10)

model = LinearRegression()
model.fit(x_train.values,y_train.values)

evaluate(model, x_train, y_train, x_test, y_test)

cross_validation(dataset, model, x, y)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

Train accuracy 0.9709489821503465
Test accuracy 0.9705902883448609
Avg accuracy: 0.9619994532674138

In [16]:
threshold = model.predict([ [True, 863,	602,	503,	604,	855,	1200,	3052,	3852,	3948,	3280,	3266,	3470,	3874,	4225,	6000,	5367,	4759,	5059,	4182,	3118,	2010,	1727,	2965,	2655] ])
print(threshold)

[4217.6018751]