In [15]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import sys

In [16]:
df = 'https://drive.google.com/uc?export=download&id=19DIL99UGIzhPZQ_VDuyrDmGPvy5VMGAn'

#raw_dataset = pd.read_csv(df, na_values='?', comment='\t', skipinitialspace=True)
raw_dataset = pd.read_csv(df)

In [17]:
dataset = raw_dataset.copy()
pd.set_option("display.max_columns", None)
dataset.head()

,station_key,full_name,latitude,longitude,daily_total,day_of_week,public_holiday,school_holiday,hour_00,hour_01,hour_02,hour_03,hour_04,hour_05,hour_06,hour_07,hour_08,hour_09,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,congestion_threshold
0,57299,"Western Motorway, South of Ponds Road",-33.806267,150.922424,70880,Friday,False,False,863,602,503,604,855,1595,3052,3852,3948,3280,3266,3470,3874,4225,5049,5367,4759,5059,4182,3118,2010,1727,2965,2655,4294
1,56667,"Southern Cross Drive, East of Mill Pond Drive",-33.936520,151.198883,60571,Friday,False,False,173,112,85,123,380,1702,4315,4652,4018,3785,3473,3378,3209,3064,3136,3278,3601,3945,4005,3279,2363,1990,1660,845,2622
2,55414,"Western Distributor, South of Pyrmont Bridge Road",-33.873138,151.194107,54579,Saturday,False,False,1929,1508,896,631,688,483,905,1977,1878,2406,2900,3213,3301,3486,3446,3236,3017,2836,3029,3266,3227,2230,1952,2139,2589
3,56708,"Victoria Road, South of Robert Street",-33.867317,151.175568,48886,Friday,False,False,469,243,197,180,346,1099,3026,3891,3796,3394,2893,2638,2536,2542,2433,2587,2626,2743,3008,2540,1545,1345,1496,1313,2070
4,57516,"Western Motorway, South of Barker Street",-33.783550,150.765106,44912,Thursday,False,False,233,223,201,351,931,3050,4166,4589,3873,2816,2132,2124,2117,2117,2212,2490,2488,2471,1777,1306,1128,1076,694,347,1992

In [21]:
def pre_processing(dataframe):
    features = dataframe.iloc[:, 0:32]
    columns_drop = ['station_key', 'day_of_week', 'public_holiday', 'school_holiday', 'full_name', 'latitude', 'longitude', 'daily_total']
    #columns_drop = ['station_key', 'full_name', 'latitude', 'longitude', 'daily_total']
    features = features.drop(columns_drop, axis=1)
    dataframe = dataset.dropna()
    target = dataframe.iloc[:, 32]
    
    return features, target

In [19]:
def evaluate(model, x_train, y_train, x_test, y_test ):
    if(model == None):
        print("Model does not exist")
        return

    print(f"Train accuracy {model.score(x_train,y_train)} ")
    print(f"Test accuracy {model.score(x_test,y_test)} ")
    return

In [22]:
x, y = pre_processing(dataset)
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=10)
    
model = LinearRegression()
model.fit(x_train.values,y_train.values)

evaluate(model, x_train, y_train, x_test, y_test)

Train accuracy 1.0
Test accuracy 0.9661177683103345

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

In [24]:
threshold = model.predict([ [200,	602,	7000,	604,	855,	3600,	3052,	3852,	3948,	3280,	3266,	
                             7000,	3874,	4225,	5049,	5367,	4759,	5059,	4182,	3118,	2010,	1727,	2965,	2655] ])
print(threshold)

[4434.98623827]